In [4]:
arquivo = open(r".\data\dom_casmurro.txt",encoding="utf-8")
texto = arquivo.read()
len(texto)

381375

In [5]:
texto = texto.lower()
palavras = texto.split()
len(palavras)

65707

In [6]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela.head()

    palavra
0       dom
1  casmurro
2       por
3   machado
4        de

In [7]:
tabela.tail()

      palavra
65702       é
65703    bem,
65704       e
65705       o
65706  resto?

In [8]:
tabela["proxima_palavra"] = tabela["palavra"].shift(-1)
tabela.head()

    palavra proxima_palavra
0       dom        casmurro
1  casmurro             por
2       por         machado
3   machado              de
4        de           assis

In [9]:
tabela.tail()

      palavra proxima_palavra
65702       é            bem,
65703    bem,               e
65704       e               o
65705       o          resto?
65706  resto?             NaN

In [10]:
tabela = tabela.dropna()
tabela

        palavra proxima_palavra
0           dom        casmurro
1      casmurro             por
2           por         machado
3       machado              de
4            de           assis
...         ...             ...
65701   cxlviii               é
65702         é            bem,
65703      bem,               e
65704         e               o
65705         o          resto?

[65706 rows x 2 columns]

In [73]:
filtro = tabela["palavra"] == "me"
tabela[filtro].head()

    palavra proxima_palavra
178      me        zanguei.
378      me            põem
407      me            vexa
427      me           criei
653      me       faltassem

In [74]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
não            0.030675
fez            0.024540
disse          0.024540
lembra         0.018405
deu            0.018405
                 ...
atravessou     0.002045
deitou         0.002045
respondeu.     0.002045
faltarem       0.002045
consolassem    0.002045
Name: proportion, Length: 353, dtype: float64

In [75]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'não'