Conceito de n-gramas

In [45]:
frase = "O amor é lindo o amor é forte e o amor vence tudo"

In [46]:
palavras = frase.split()
palavras

['O',
 'amor',
 'é',
 'lindo',
 'o',
 'amor',
 'é',
 'forte',
 'e',
 'o',
 'amor',
 'vence',
 'tudo']

In [47]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela

   palavra
0        O
1     amor
2        é
3    lindo
4        o
5     amor
6        é
7    forte
8        e
9        o
10    amor
11   vence
12    tudo

In [48]:
tabela["proxima_palavra"] = tabela["palavra"].shift(-1)
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é           lindo
3    lindo               o
4        o            amor
5     amor               é
6        é           forte
7    forte               e
8        e               o
9        o            amor
10    amor           vence
11   vence            tudo
12    tudo             NaN

In [49]:
tabela = tabela.dropna()
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é           lindo
3    lindo               o
4        o            amor
5     amor               é
6        é           forte
7    forte               e
8        e               o
9        o            amor
10    amor           vence
11   vence            tudo

In [56]:
filtro = tabela["palavra"] == "lindo"
tabela[filtro]

  palavra proxima_palavra
3   lindo               o

In [57]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
o    1.0
Name: proportion, dtype: float64

In [58]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'o'